### ISSUE TITLE
Powiadomienie o dodanym podobnym zleceniu

### ISSUE THREAD

**Issue by karpiq24** [karpiq24/django-klima-kar#228]
Jeśli podobne (kontrahent, pojazd, podzespół) zlecenie zostało już dodane należy wyświetlić jakieś powiadomienie.

**Comment by jskrp** [comment]
Chodzi o jasny komunikat, że już jest zlecenie otwarte albo gotowe albo wstrzymane i użytkownik powinien raczej przejść do tamtego zlecenia zamiast tworzyć nowe. Chyba, że naprawdę potrzebne jest osobne zlecenie to powinno się dać otworzyć drugie.
